# Configuration file for add_to_apple_photos_watcher.py
# Controls output verbosity and display options

# Display Options
display:
  # Whether to print title information for each photo
  print_titles: false
  
  # Whether to print caption information for each photo  
  print_captions: false
  
  # Whether to print titles only when they contain category format (colon)
  print_titles_if_category: true
  
  # Whether to print captions only when they contain category format (colon)
  print_captions_if_category: true

# Processing Options
processing:
  # Batch size for processing assets (default: 1000)
  batch_size: 1000
  
  # Maximum number of assets to process (0 = unlimited)
  max_assets: 0
  
  # Pause duration in seconds after every 1000 additions
  pause_duration: 10

# Category Detection Options
category_detection:
  # Whether to check titles for category format (colon detection)
  check_titles: true
  
  # Whether to check captions for category format (colon detection)
  check_captions: true

# Debug Options
debug:
  # Show detailed debug output for category detection
  show_category_debug: true
  
  # Show progress updates every N additions
  progress_interval: 50
  
  # Show batch summaries
  show_batch_summaries: true
  
  # Show detailed photokit caption extraction logging
  log_photokit_extraction: false 
